import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { usePlayer } from "../context/PlayerContext";
import { aiService } from "../services/apiService";
import { useAuth } from "../context/AuthContext";
import { Plus, Heart, Sparkles, Play, Pause, X } from "lucide-react";
import PlaylistCover from "../components/playlist/PlaylistCover";
import CreatePlaylistModal from "../components/CreatePlaylistModal";
import { playlistService } from "../services/apiService";

export default function Library() {
  const navigate = useNavigate();
  const { 
    currentTrack, 
    isPlaying, 
    playTrack, 
    togglePlay, 
    likedSongs, 
    playlists, 
    createPlaylist, 
    setNowPlayingOpen, 
    setPreviewTrack 
  } = usePlayer();
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState("liked");
  const [generating, setGenerating] = useState(false);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [newPlaylistName, setNewPlaylistName] = useState("");
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showAIModal, setShowAIModal] = useState(false);
  const [creatingPlaylist, setCreatingPlaylist] = useState(false);
  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [createdPlaylist, setCreatedPlaylist] = useState(null);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiCount, setAiCount] = useState(10);

  const handleManualCreate = () => {
    if (!newPlaylistName.trim()) return;
    createPlaylist(newPlaylistName.trim(), "Custom playlist created in library.");
    setNewPlaylistName("");
    setShowCreateForm(false);
    setActiveTab("playlists");
  };

  const openCreatePlaylistModal = () => {
    setShowCreateModal(true);
    setShowCreateForm(false);
  };

  const handleCreatePlaylist = async (payload) => {
    setCreatingPlaylist(true);
    try {
      const response = await playlistService.create(payload);
      const created = response?.data?.playlist || response?.data;

      if (created) {
        createPlaylist(
          created.name || payload.name,
          created.description || payload.description,
          created.coverImage || payload.coverImage || "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
          [],
          user?.username || user?.email || "You",
          payload.isPrivate === false ? false : payload.isPrivate,
          created.shareUrl || payload.shareUrl
        );
      } else {
        createPlaylist(
          payload.name,
          payload.description || "Custom playlist created in library.",
          payload.coverImage || "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
          [],
          user?.username || user?.email || "You",
          payload.isPrivate === false ? false : payload.isPrivate,
          undefined
        );
      }

      setActiveTab("playlists");
      setShowCreateModal(false);
    } catch (error) {
      console.error("Failed to create playlist", error);
      createPlaylist(
        payload.name,
        payload.description || "Custom playlist created in library.",
        payload.coverImage || "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=500&auto=format&fit=crop&q=60",
        [],
        user?.username || user?.email || "You",
        payload.isPrivate === false ? false : payload.isPrivate,
        undefined
      );
      setActiveTab("playlists");
      setShowCreateModal(false);
    } finally {
      setCreatingPlaylist(false);
    }
  };

  // ── AI Playlist Generation ──
  const handleAIGenerate = async (prompt, count) => {
    setGenerating(true);
    
    try {
      const response = await aiService.generate({
        prompt: prompt,
        count: count || 10,
      });

      const data = response.data;

      if (data.success) {
        const aiSongs = data.playlist.songs.map(song => ({
          id: song.videoId || song.id,
          _id: song.videoId || song.id,
          videoId: song.videoId || song.id,
          title: song.title,
          artist: song.artist || song.channelTitle,
          thumbnail: song.thumbnail || '',
          thumbnail_medium: song.thumbnail || '',
          coverArtUrl: song.thumbnail || '',
          duration: song.duration || 0,
          duration_string: song.duration_string || '0:00',
          url: song.url || `https://www.youtube.com/watch?v=${song.videoId || song.id}`,
          audioUrl: null,
          type: 'song',
          source: 'ai-generated'
        }));

        const playlistName = data.playlist.title || `🎵 AI Playlist: ${prompt.slice(0, 20)}`;
        const playlistDescription = data.playlist.description || `Generated by Melodia AI. Prompt: "${prompt}"`;
        const coverImage = data.playlist.coverImage || 
                          aiSongs[0]?.thumbnail || 
                          "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=300&auto=format&fit=crop&q=60";

        // Create the playlist
        const newPlaylist = createPlaylist(
          playlistName,
          playlistDescription,
          coverImage,
          aiSongs,
          true
        );

        // Store and show success modal
        setCreatedPlaylist(newPlaylist);
        setShowSuccessModal(true);
      } else {
        alert('Failed to generate playlist: ' + (data.error || 'Unknown error'));
      }
    } catch (error) {
      console.error('AI Playlist generation error:', error);
      if (error.response) {
        alert(`Server error: ${error.response.data.error || error.response.status}`);
      } else {
        alert('Error generating playlist. Please make sure the server is running.');
      }
    } finally {
      setGenerating(false);
    }
  };

  // ── Handle row click ──
  const handleRowClick = (song) => {
    const songId = song.id || song._id || song.videoId;
    const currentId = currentTrack ? (currentTrack.id || currentTrack._id || currentTrack.videoId) : null;
    const isCurrent = currentTrack && songId === currentId;
    
    if (isCurrent) {
      if (!isPlaying) togglePlay();
    } else {
      if (songId) {
        playTrack(song, likedSongs);
      }
    }
  };

  const isSongCurrent = (song) => {
    if (!currentTrack) return false;
    const songId = song.id || song._id || song.videoId;
    const currentId = currentTrack.id || currentTrack._id || currentTrack.videoId;
    return songId === currentId;
  };

  const formatDuration = (secs) => {
    if (isNaN(secs)) return "0:00";
    const m = Math.floor(secs / 60);
    const s = Math.floor(secs % 60);
    return `${m}:${s < 10 ? "0" : ""}${s}`;
  };

  return (
    <div className="p-6 md:p-8 space-y-8 text-left animate-in fade-in duration-200" style={{ fontFamily: "Urbanist, sans-serif" }}>
      {/* Header - same as before */}
      <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4">
        <div>
          <h1 className="text-2xl font-black text-white mb-2">My Library</h1>
          <p className="text-sm text-muted-foreground">Manage your playlists and liked songs collections.</p>
        </div>

        {/* Playlist Actions */}
        <div className="flex flex-col sm:flex-row gap-3">
          {showCreateForm ? (
            <div className="flex items-center gap-2 bg-[#111120] border border-white/10 rounded-xl p-1 animate-in fade-in slide-in-from-right-2 duration-200">
              <input
                type="text"
                placeholder="Playlist name..."
                value={newPlaylistName}
                onChange={(e) => setNewPlaylistName(e.target.value)}
                className="bg-transparent text-xs text-white px-3 py-1.5 outline-none placeholder-muted-foreground font-semibold"
                autoFocus
              />
              <button
                onClick={handleManualCreate}
                disabled={!newPlaylistName.trim()}
                className="px-3 py-1.5 rounded-lg bg-primary text-white text-xs font-bold disabled:opacity-40 transition-opacity cursor-pointer"
              >
                Create
              </button>
              <button
                onClick={() => { setShowCreateForm(false); setNewPlaylistName(""); }}
                className="px-2 py-1.5 rounded-lg text-muted-foreground hover:text-white text-xs font-semibold transition-colors cursor-pointer"
              >
                Cancel
              </button>
            </div>
          ) : (
            <div className="flex gap-2 flex-wrap">
              <button
                onClick={openCreatePlaylistModal}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-white text-xs font-bold transition-all cursor-pointer w-fit"
              >
                <Plus className="w-3.5 h-3.5" />
                Create Playlist
              </button>
              
              <button
                onClick={() => setShowAIModal(true)}
                disabled={generating}
                className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary/20 border border-primary/40 hover:bg-primary/30 text-white text-xs font-bold transition-all disabled:opacity-50 cursor-pointer w-fit"
              >
                <Sparkles className="w-3.5 h-3.5" />
                {generating ? "Generating..." : "Generate Smart Playlist"}
              </button>
            </div>
          )}
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 bg-[#111120] border border-border/40 rounded-xl p-1 w-fit">
        {(["liked", "playlists"]).map((t) => (
          <button
            key={t}
            onClick={() => setActiveTab(t)}
            className={`px-5 py-2 rounded-lg text-xs font-bold transition-all capitalize cursor-pointer ${
              activeTab === t ? "bg-primary text-white shadow-lg shadow-primary/20" : "text-muted-foreground hover:text-foreground"
            }`}
          >
            {t === "liked" ? "Liked Songs" : "Playlists"}
          </button>
        ))}
      </div>

      {/* Content - Liked Songs */}
      {activeTab === "liked" && (
        <section className="space-y-3">
          {likedSongs.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center border border-dashed border-border rounded-3xl bg-card/20">
              <Heart className="w-12 h-12 text-muted-foreground mb-4" />
              <p className="text-base font-bold text-white mb-1">No liked songs yet</p>
              <p className="text-xs text-muted-foreground max-w-xs">Explore the catalogue and heart tracks you love to see them here.</p>
            </div>
          ) : (
            <div className="space-y-1">
              {/* Row headers */}
              <div className="flex items-center gap-4 px-4 py-2 text-xs font-bold text-muted-foreground uppercase tracking-widest border-b border-border/25 select-none">
                <span className="w-8 text-center">#</span>
                <span className="flex-grow">Title</span>
                <span className="hidden md:block w-32">Genre</span>
                <span className="w-12 text-right">Time</span>
              </div>

              {likedSongs.map((song, i) => {
                const isCurrent = isSongCurrent(song);
                const showPlaying = isCurrent && isPlaying;
                return (
                  <div
                    key={song.id || song._id || song.videoId || i}
                    onClick={() => handleRowClick(song)}
                    className={`group flex items-center gap-4 px-4 py-3 rounded-xl cursor-pointer transition-all duration-150 ${
                      isCurrent ? "bg-primary/10 border border-primary/25" : "hover:bg-card/60 border border-transparent"
                    }`}
                  >
                    <div className="w-8 flex items-center justify-center shrink-0">
                      {isCurrent ? (
                        showPlaying ? (
                          <span className="flex gap-0.5 items-end h-4">
                            <span className="w-0.5 bg-primary animate-pulse" style={{ height: "60%" }} />
                            <span className="w-0.5 bg-primary animate-pulse" style={{ height: "100%" }} />
                            <span className="w-0.5 bg-primary animate-pulse" style={{ height: "40%" }} />
                          </span>
                        ) : (
                          <Pause className="w-3.5 h-3.5 text-primary fill-primary" />
                        )
                      ) : (
                        <span className="text-xs font-mono text-muted-foreground group-hover:hidden">
                          {String(i + 1).padStart(2, "0")}
                        </span>
                      )}
                      {!isCurrent && (
                        <Play className="w-3.5 h-3.5 text-primary fill-primary hidden group-hover:block" />
                      )}
                    </div>
                    <img
                      onClick={(e) => {
                        e.stopPropagation();
                        if (!isCurrent) setPreviewTrack(song);
                        setNowPlayingOpen(true);
                      }}
                      src={song.thumbnail || song.thumbnail_medium || song.coverArtUrl || "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200&h=200&fit=crop&auto=format"}
                      alt={song.title}
                      className="w-10 h-10 rounded-lg object-cover shrink-0 bg-[#111120] cursor-pointer hover:opacity-85 transition-opacity"
                    />
                    <div className="flex-grow min-w-0 text-left">
                      <p className={`text-sm font-bold truncate ${isCurrent ? "text-primary" : "text-white"}`}>
                        {song.title}
                      </p>
                      <p className="text-xs text-muted-foreground truncate">{song.artist}</p>
                    </div>
                    <span className="hidden md:block text-xs text-muted-foreground w-32 truncate text-left">{song.genre || "Acoustics"}</span>
                    <span className="text-xs text-muted-foreground font-mono w-12 text-right">{formatDuration(song.duration)}</span>
                  </div>
                );
              })}
            </div>
          )}
        </section>
      )}

      {/* Content - Playlists */}
      {activeTab === "playlists" && (
        <section className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="text-sm text-muted-foreground">Your saved collections</div>
            <button
              onClick={openCreatePlaylistModal}
              className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-white transition-all hover:bg-white/10"
            >
              <Plus className="h-3.5 w-3.5" />
              Add Playlist
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div
            onClick={() => setActiveTab("liked")}
            className="flex items-center gap-4 rounded-2xl bg-gradient-to-br from-primary/20 to-accent/15 border border-primary/20 p-4 cursor-pointer hover:border-primary/40 transition-all group text-left"
          >
            <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-primary to-accent flex items-center justify-center shadow-lg shrink-0">
              <Heart className="w-7 h-7 text-white fill-white animate-pulse" />
            </div>
            <div>
              <p className="text-sm font-bold text-white">Liked Songs Collection</p>
              <p className="text-xs text-muted-foreground">{likedSongs.length} tracks saved</p>
            </div>
          </div>

          {playlists.map((pl) => (
            <div
              key={pl.id}
              onClick={() => navigate(`/playlist/${pl.id}`)}
              className="flex items-center gap-4 rounded-2xl bg-card border border-border p-4 cursor-pointer hover:border-primary/30 hover:shadow-lg transition-all group text-left"
            >
              <div className="w-16 h-16 rounded-xl overflow-hidden bg-[#111120] shrink-0">
                <PlaylistCover
                  songs={pl.songs || []}
                  coverImageUrl={pl.coverImageUrl}
                  name={pl.name}
                  isAi={pl.isAiGenerated}
                  iconSize={28}
                />
              </div>
              <div className="min-w-0 flex-1">
                <p className="text-sm font-bold text-white truncate group-hover:text-primary transition-colors">
                  {pl.name}
                </p>
                <p className="text-xs text-muted-foreground mt-0.5 truncate">{pl.description}</p>
                <span className="inline-block mt-1 text-[10px] text-muted-foreground">
                  Created by {pl.createdBy || user?.username || 'You'}
                </span>
                <span className="inline-block mt-1.5 text-[10px] bg-primary/10 text-primary border border-primary/20 px-2 py-0.5 rounded-full font-bold">
                  {pl.songs ? pl.songs.length : 0} Tracks
                </span>
              </div>
            </div>
          ))}
          </div>
        </section>
      )}

      <CreatePlaylistModal
        isOpen={showCreateModal}
        onClose={() => setShowCreateModal(false)}
        onCreate={handleCreatePlaylist}
        submitting={creatingPlaylist}
      />

      {/* ── AI Playlist Generator Modal ── */}
      {showAIModal && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 animate-in fade-in duration-200">
          <div className="bg-[#1a1a2e] rounded-2xl p-6 max-w-md w-full mx-4 border border-white/10 shadow-2xl">
            <div className="flex justify-between items-center mb-4">
              <h2 className="text-xl font-bold text-white">🤖 Generate AI Playlist</h2>
              <button
                onClick={() => {
                  setShowAIModal(false);
                  setAiPrompt('');
                }}
                className="text-muted-foreground hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
            
            <p className="text-sm text-muted-foreground mb-4">
              Describe the vibe, mood, or theme for your perfect playlist.
            </p>
            
            <label className="block mb-4">
              <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Your Prompt</span>
              <input
                type="text"
                value={aiPrompt}
                onChange={(e) => setAiPrompt(e.target.value)}
                placeholder="e.g., sad bollywood songs for a rainy day"
                className="w-full bg-[#111120] border border-white/10 rounded-xl px-4 py-3 text-white text-sm outline-none focus:border-primary/50 transition-colors mt-1"
                autoFocus
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && aiPrompt.trim()) {
                    handleAIGenerate(aiPrompt, aiCount);
                    setShowAIModal(false);
                    setAiPrompt('');
                  }
                }}
              />
            </label>
            
            <label className="block mb-6">
              <span className="text-xs font-bold text-muted-foreground uppercase tracking-wider">Number of Songs: {aiCount}</span>
              <input
                type="range"
                min="5"
                max="20"
                value={aiCount}
                onChange={(e) => setAiCount(Number(e.target.value))}
                className="w-full mt-1 accent-primary"
              />
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>5</span>
                <span>20</span>
              </div>
            </label>
            
            <div className="flex gap-3">
              <button
                onClick={() => {
                  setShowAIModal(false);
                  setAiPrompt('');
                }}
                className="flex-1 bg-white/5 border border-white/10 rounded-xl py-2.5 text-white text-sm font-bold hover:bg-white/10 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={() => {
                  if (aiPrompt.trim()) {
                    handleAIGenerate(aiPrompt, aiCount);
                    setShowAIModal(false);
                    setAiPrompt('');
                  } else {
                    alert('Please describe what kind of playlist you want!');
                  }
                }}
                disabled={generating}
                className="flex-1 bg-gradient-to-r from-primary to-accent rounded-xl py-2.5 text-white text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
              >
                {generating ? 'Generating...' : '✨ Generate'}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* ── Success Modal ── */}
      {showSuccessModal && createdPlaylist && (
        <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50 animate-in fade-in duration-200">
          <div className="bg-[#1a1a2e] rounded-2xl p-6 max-w-md w-full mx-4 border border-white/10 shadow-2xl">
            <div className="text-center">
              <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-green-500/20 flex items-center justify-center">
                <svg className="w-8 h-8 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" />
                </svg>
              </div>
              
              <h2 className="text-xl font-bold text-white mb-2">✅ Playlist Created!</h2>
              <p className="text-sm text-muted-foreground mb-1">
                <span className="text-white font-semibold">{createdPlaylist.name}</span>
              </p>
              <p className="text-xs text-muted-foreground mb-6">
                {createdPlaylist.songs?.length || 0} songs added
              </p>
              
              <div className="flex gap-3">
                <button
                  onClick={() => {
                    setShowSuccessModal(false);
                    setCreatedPlaylist(null);
                    setActiveTab("playlists");
                  }}
                  className="flex-1 bg-white/5 border border-white/10 rounded-xl py-2.5 text-white text-sm font-bold hover:bg-white/10 transition-colors"
                >
                  Stay Here
                </button>
                <button
                  onClick={() => {
                    setShowSuccessModal(false);
                    setCreatedPlaylist(null);
                    navigate(`/playlist/${createdPlaylist.id}`);
                  }}
                  className="flex-1 bg-gradient-to-r from-primary to-accent rounded-xl py-2.5 text-white text-sm font-bold hover:opacity-90 transition-opacity"
                >
                  View Playlist 🎵
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}