import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

const FEATURES = [
  {
    icon: '☁️',
    title: 'Cloud Backup',
    desc: 'All your music, playlists, and settings securely backed up to the cloud. Access from anywhere, on any device.',
  },
  {
    icon: '🤖',
    title: 'AI Playlists',
    desc: 'Smart playlists generated by AI based on your mood, activity, and listening history.',
  },
  {
    icon: '🎵',
    title: 'Playlist Management',
    desc: 'Organize, sort, and curate your playlists with powerful drag-and-drop tools.',
  },
  {
    icon: '🔍',
    title: 'Live Search',
    desc: 'Instant real-time search across 80 million tracks, artists, albums, and podcasts.',
  },
  {
    icon: '💡',
    title: 'Mind Share',
    desc: 'Share your musical mind — export your taste profile and discover your sonic twin.',
  },
  {
    icon: '🎙️',
    title: 'Record Draft',
    desc: 'Capture voice memos and draft recordings directly in-app, linked to your library.',
  },
]

const TRENDING = [
  { title: 'Blinding Lights', artist: 'The Weeknd', plays: '2.4B', img: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=300&h=300&fit=crop&auto=format' },
  { title: 'As It Was', artist: 'Harry Styles', plays: '1.9B', img: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=300&h=300&fit=crop&auto=format' },
  { title: 'Flowers', artist: 'Miley Cyrus', plays: '1.6B', img: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=300&h=300&fit=crop&auto=format' },
  { title: 'Unholy', artist: 'Sam Smith', plays: '1.3B', img: 'https://images.unsplash.com/photo-1571330735066-03aaa9429d89?w=300&h=300&fit=crop&auto=format' },
  { title: 'Anti-Hero', artist: 'Taylor Swift', plays: '1.1B', img: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=300&h=300&fit=crop&auto=format' },
  { title: 'Bad Habit', artist: 'Steve Lacy', plays: '980M', img: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=300&h=300&fit=crop&auto=format' },
]

const NAV_LINKS = [
  { label: 'Home', target: 'hero' },
  { label: 'Features', target: 'features' },
  { label: 'Trending', target: 'trending' },
  { label: 'Contact', target: 'contact' },
]

function scrollTo(id) {
  const el = document.getElementById(id)
  if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
}

function GlowOrb({ x, y, color, size }) {
  return (
    <div
      style={{
        position: 'absolute',
        left: x,
        top: y,
        width: size,
        height: size,
        background: color,
        borderRadius: '50%',
        filter: 'blur(90px)',
        opacity: 0.28,
        pointerEvents: 'none',
      }}
    />
  )
}

function MelodiaLogo({ size = 32 }) {
  const r = size * 0.44
  const cx = size * 0.5
  const cy = size * 0.5

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} fill="none">
      <defs>
        <linearGradient id="logoRing" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#c084fc" />
          <stop offset="100%" stopColor="#7c3aed" />
        </linearGradient>
        <linearGradient id="logoNote" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stopColor="#e9d5ff" />
          <stop offset="100%" stopColor="#a855f7" />
        </linearGradient>
      </defs>
      <circle cx={cx} cy={cy} r={r} stroke="url(#logoRing)" strokeWidth={size * 0.055} fill="none" />
      <g transform={`translate(${cx - size * 0.14} ${cy - size * 0.18})`}>
        <rect x={size * 0.155} y={0} width={size * 0.058} height={size * 0.24} rx={size * 0.02} fill="url(#logoNote)" />
        <path
          d={`M${size * 0.213} 0 Q${size * 0.3} ${size * 0.07} ${size * 0.213} ${size * 0.14}`}
          stroke="url(#logoNote)"
          strokeWidth={size * 0.05}
          fill="none"
          strokeLinecap="round"
        />
        <ellipse
          cx={size * 0.1}
          cy={size * 0.265}
          rx={size * 0.1}
          ry={size * 0.075}
          transform={`rotate(-15 ${size * 0.1} ${size * 0.265})`}
          fill="url(#logoNote)"
        />
      </g>
    </svg>
  )
}

function HeadphoneVisual() {
  return (
    <div style={{ position: 'relative', width: 340, height: 340, flexShrink: 0 }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          background: 'radial-gradient(circle at 55% 50%, rgba(147,51,234,0.45) 0%, rgba(168,85,247,0.2) 40%, transparent 70%)',
          borderRadius: '50%',
        }}
      />
      <div
        style={{
          position: 'absolute',
          inset: '20px',
          background: 'radial-gradient(circle at 50% 50%, rgba(124,58,237,0.2) 0%, transparent 65%)',
          borderRadius: '50%',
        }}
      />
      <svg viewBox="0 0 340 340" width="340" height="340" style={{ position: 'absolute', inset: 0 }}>
        <defs>
          <linearGradient id="rg1" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#a855f7" stopOpacity="1" />
            <stop offset="100%" stopColor="#a855f7" stopOpacity="0.4" />
          </linearGradient>
          <linearGradient id="rg2" x1="100%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stopColor="#7c3aed" stopOpacity="0.85" />
            <stop offset="100%" stopColor="#a855f7" stopOpacity="0.3" />
          </linearGradient>
          <linearGradient id="rg3" x1="0%" y1="100%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#9333ea" stopOpacity="0.9" />
            <stop offset="100%" stopColor="#c084fc" stopOpacity="0.25" />
          </linearGradient>
          <filter id="glow">
            <feGaussianBlur stdDeviation="3" result="b" />
            <feMerge>
              <feMergeNode in="b" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>
        <ellipse cx="170" cy="170" rx="130" ry="52" fill="none" stroke="url(#rg1)" strokeWidth="2.5" transform="rotate(-20 170 170)" filter="url(#glow)" opacity="0.9" />
        <ellipse cx="170" cy="170" rx="130" ry="52" fill="none" stroke="url(#rg2)" strokeWidth="1.5" transform="rotate(40 170 170)" filter="url(#glow)" opacity="0.75" />
        <ellipse cx="170" cy="170" rx="130" ry="52" fill="none" stroke="url(#rg3)" strokeWidth="2" transform="rotate(100 170 170)" filter="url(#glow)" opacity="0.8" />
        <ellipse cx="170" cy="170" rx="85" ry="34" fill="none" stroke="#c084fc" strokeWidth="1.5" transform="rotate(-20 170 170)" opacity="0.55" />
        <ellipse cx="170" cy="170" rx="85" ry="34" fill="none" stroke="#c084fc" strokeWidth="1" transform="rotate(40 170 170)" opacity="0.45" />
        <circle cx="170" cy="170" r="38" fill="url(#rg1)" opacity="0.8" filter="url(#glow)" />
        <circle cx="170" cy="170" r="28" fill="#09091a" opacity="0.92" />
        <circle cx="162" cy="163" r="10" fill="#c084fc" opacity="0.65" />
        <circle cx="300" cy="130" r="4" fill="#a855f7" opacity="0.8" filter="url(#glow)" />
        <circle cx="60" cy="220" r="3" fill="#a855f7" opacity="0.7" filter="url(#glow)" />
        <circle cx="290" cy="240" r="2.5" fill="#9333ea" opacity="0.6" />
        <circle cx="80" cy="100" r="2" fill="#a855f7" opacity="0.5" />
        <line x1="170" y1="132" x2="170" y2="90" stroke="#a855f7" strokeWidth="1" opacity="0.38" strokeDasharray="3 4" />
        <line x1="208" y1="170" x2="250" y2="170" stroke="#c084fc" strokeWidth="1" opacity="0.38" strokeDasharray="3 4" />
      </svg>
    </div>
  )
}

function BrainVisual() {
  const nodes = [
    [130, 100],
    [80, 60],
    [180, 60],
    [60, 120],
    [200, 120],
    [100, 150],
    [160, 150],
    [130, 40],
    [220, 90],
    [40, 90],
  ]

  const edges = [
    [[130, 100], [80, 60]],
    [[130, 100], [180, 60]],
    [[130, 100], [60, 120]],
    [[130, 100], [200, 120]],
    [[80, 60], [130, 40]],
    [[180, 60], [130, 40]],
    [[80, 60], [40, 90]],
    [[180, 60], [220, 90]],
    [[60, 120], [100, 150]],
    [[200, 120], [160, 150]],
    [[100, 150], [130, 100]],
    [[160, 150], [130, 100]],
  ]

  return (
    <div style={{ position: 'relative', width: 260, height: 200, flexShrink: 0 }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          background: 'radial-gradient(circle at 50% 50%, rgba(147,51,234,0.45) 0%, transparent 70%)',
          borderRadius: '50%',
        }}
      />
      <svg viewBox="0 0 260 200" width="260" height="200" style={{ position: 'absolute', inset: 0 }}>
        <defs>
          <linearGradient id="bg2" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stopColor="#a855f7" />
            <stop offset="100%" stopColor="#a855f7" />
          </linearGradient>
          <filter id="glow2">
            <feGaussianBlur stdDeviation="4" result="b" />
            <feMerge>
              <feMergeNode in="b" />
              <feMergeNode in="SourceGraphic" />
            </feMerge>
          </filter>
        </defs>
        {edges.map(([start, end], i) => (
          <line key={i} x1={start[0]} y1={start[1]} x2={end[0]} y2={end[1]} stroke="#9333ea" strokeWidth="1" opacity="0.4" />
        ))}
        {nodes.map(([cx, cy], i) => (
          <circle key={i} cx={cx} cy={cy} r="5" fill="url(#bg2)" opacity="0.8" filter="url(#glow2)" />
        ))}
        <circle cx="130" cy="100" r="12" fill="#7c3aed" opacity="0.6" filter="url(#glow2)" />
        <circle cx="130" cy="40" r="8" fill="#a855f7" opacity="0.7" filter="url(#glow2)" />
      </svg>
    </div>
  )
}

export default function Opening() {
  const navigate = useNavigate()
  const [scrolled, setScrolled] = useState(false)
  const [activeNav, setActiveNav] = useState('hero')

  useEffect(() => {
    const onScroll = () => {
      setScrolled(window.scrollY > 20)
      const sections = ['hero', 'features', 'trending', 'contact']
      for (const id of [...sections].reverse()) {
        const el = document.getElementById(id)
        if (el && window.scrollY >= el.offsetTop - 120) {
          setActiveNav(id)
          break
        }
      }
    }

    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  return (
    <div style={{ background: '#070710', color: '#e2e8f0', fontFamily: "'Inter', system-ui, sans-serif", minHeight: '100vh', overflowX: 'hidden' }}>
      <nav
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          zIndex: 50,
          background: scrolled ? 'rgba(7,7,16,0.88)' : 'transparent',
          backdropFilter: scrolled ? 'blur(18px)' : 'none',
          borderBottom: scrolled ? '1px solid rgba(147,51,234,0.15)' : 'none',
          transition: 'all 0.3s ease',
          padding: '0 40px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          height: 64,
        }}
      >
        <button
          onClick={() => scrollTo('hero')}
          style={{ display: 'flex', alignItems: 'center', gap: 10, background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}
        >
          <MelodiaLogo size={36} />
          <span style={{ fontSize: 19, fontWeight: 700, letterSpacing: '-0.025em' }}>
            <span style={{ color: '#fff' }}>Melo</span>
            <span style={{ background: 'linear-gradient(135deg, #c084fc, #7c3aed)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
              dia
            </span>
          </span>
        </button>

        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }} className="nav-links">
          {NAV_LINKS.map(({ label, target }) => {
            const active = activeNav === target
            return (
              <button
                key={label}
                onClick={() => scrollTo(target)}
                style={{
                  background: active ? 'rgba(147,51,234,0.12)' : 'none',
                  border: active ? '1px solid rgba(147,51,234,0.25)' : '1px solid transparent',
                  color: active ? '#d8b4fe' : '#94a3b8',
                  fontSize: 14,
                  fontWeight: 500,
                  cursor: 'pointer',
                  padding: '7px 16px',
                  borderRadius: 8,
                  transition: 'all 0.2s',
                }}
                onMouseEnter={(e) => {
                  if (!active) {
                    e.currentTarget.style.color = '#e2e8f0'
                    e.currentTarget.style.background = 'rgba(255,255,255,0.05)'
                  }
                }}
                onMouseLeave={(e) => {
                  if (!active) {
                    e.currentTarget.style.color = '#94a3b8'
                    e.currentTarget.style.background = 'none'
                  }
                }}
              >
                {label}
              </button>
            )
          })}
        </div>

        <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
          <button
            onClick={() => navigate('/login')}
            style={{
              background: 'none',
              border: 'none',
              color: '#94a3b8',
              fontSize: 14,
              fontWeight: 500,
              cursor: 'pointer',
              padding: '8px 16px',
              transition: 'color 0.2s',
            }}
            onMouseEnter={(e) => (e.currentTarget.style.color = '#e2e8f0')}
            onMouseLeave={(e) => (e.currentTarget.style.color = '#94a3b8')}
          >
            Sign In
          </button>
          <button
            onClick={() => navigate('/login')}
            style={{
              background: 'linear-gradient(135deg, #9333ea, #7c3aed)',
              border: 'none',
              color: '#fff',
              fontSize: 14,
              fontWeight: 600,
              cursor: 'pointer',
              padding: '9px 20px',
              borderRadius: 8,
              transition: 'opacity 0.2s, boxShadow 0.2s',
              boxShadow: '0 0 20px rgba(147,51,234,0.35)',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.opacity = '0.9'
              e.currentTarget.style.boxShadow = '0 4px 24px rgba(147,51,234,0.55)'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.opacity = '1'
              e.currentTarget.style.boxShadow = '0 0 20px rgba(147,51,234,0.35)'
            }}
          >
            Get Started
          </button>
        </div>
      </nav>

      <section
        id="hero"
        style={{
          position: 'relative',
          minHeight: '100vh',
          display: 'flex',
          alignItems: 'center',
          padding: '100px 80px 80px',
          overflow: 'hidden',
        }}
      >
        <GlowOrb x="-120px" y="0px" color="radial-gradient(circle, #7c3aed, #3b0764)" size="600px" />
        <GlowOrb x="50%" y="-80px" color="radial-gradient(circle, #9333ea, #6d28d9)" size="420px" />
        <GlowOrb x="58%" y="30%" color="radial-gradient(circle, #a855f7, #7e22ce)" size="500px" />
        <GlowOrb x="20%" y="62%" color="radial-gradient(circle, #7c3aed, #3b0764)" size="320px" />

        <div
          style={{
            position: 'absolute',
            inset: 0,
            backgroundImage: 'linear-gradient(rgba(147,51,234,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(147,51,234,0.04) 1px, transparent 1px)',
            backgroundSize: '60px 60px',
            pointerEvents: 'none',
          }}
        />

        <div
          style={{
            position: 'relative',
            zIndex: 2,
            maxWidth: 1200,
            margin: '0 auto',
            width: '100%',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: 60,
            flexWrap: 'wrap',
          }}
        >
          <div style={{ flex: '1 1 480px', maxWidth: 560 }}>
            <div
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                background: 'rgba(147,51,234,0.1)',
                border: '1px solid rgba(147,51,234,0.28)',
                borderRadius: 999,
                padding: '6px 14px',
                marginBottom: 28,
              }}
            >
              <div style={{ width: 6, height: 6, background: '#c084fc', borderRadius: '50%' }} />
              <span style={{ fontSize: 12, color: '#d8b4fe', fontWeight: 500, letterSpacing: '0.05em' }}>
                Music Streaming App
              </span>
            </div>

            <h1
              style={{
                fontSize: 'clamp(46px, 6vw, 78px)',
                fontWeight: 800,
                lineHeight: 1.05,
                letterSpacing: '-0.03em',
                color: '#fff',
                margin: '0 0 24px',
              }}
            >
              Listen.{' '}
              <span
                style={{
                  background: 'linear-gradient(135deg, #e879f9 0%, #7c3aed 100%)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  backgroundClip: 'text',
                }}
              >
                Discover.
              </span>
              <br />
              Create.
            </h1>

            <p style={{ fontSize: 17, color: '#94a3b8', lineHeight: 1.75, marginBottom: 38, maxWidth: 460 }}>
              Stream millions of tracks, build smart playlists, and let our engine surface the music you didn't know you needed — all in one beautifully crafted app.
            </p>

            <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap', marginBottom: 52 }}>
              <button
                onClick={() => scrollTo('features')}
                style={{
                  background: 'linear-gradient(135deg, #9333ea, #7c3aed)',
                  border: 'none',
                  color: '#fff',
                  fontSize: 15,
                  fontWeight: 600,
                  cursor: 'pointer',
                  padding: '13px 28px',
                  borderRadius: 10,
                  transition: 'transform 0.15s, boxShadow 0.15s',
                  boxShadow: '0 0 30px rgba(147,51,234,0.4)',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.transform = 'translateY(-2px)'
                  e.currentTarget.style.boxShadow = '0 8px 40px rgba(147,51,234,0.6)'
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.transform = 'translateY(0)'
                  e.currentTarget.style.boxShadow = '0 0 30px rgba(147,51,234,0.4)'
                }}
              >
                ▶ Get Started Free
              </button>
              <button
                onClick={() => navigate('/login')}
                style={{
                  background: 'rgba(255,255,255,0.05)',
                  border: '1px solid rgba(255,255,255,0.11)',
                  color: '#e2e8f0',
                  fontSize: 15,
                  fontWeight: 500,
                  cursor: 'pointer',
                  padding: '13px 28px',
                  borderRadius: 10,
                  transition: 'background 0.2s',
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background = 'rgba(255,255,255,0.09)'
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = 'rgba(255,255,255,0.05)'
                }}
              >
                Learn More
              </button>
            </div>

            <div style={{ display: 'flex', gap: 44 }}>
              {['80M+', '20K+', '4.9★'].map((val, idx) => (
                <div key={idx}>
                  <div style={{ fontSize: 22, fontWeight: 700, color: '#fff' }}>{val}</div>
                  <div style={{ fontSize: 12, color: '#475569', marginTop: 2 }}>
                    {['Tracks', 'Artists', 'Rating'][idx]}
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ flex: '1 1 300px', display: 'flex', justifyContent: 'center' }}>
            <HeadphoneVisual />
          </div>
        </div>
      </section>

      <section id="features" style={{ padding: '100px 80px', position: 'relative', scrollMarginTop: '64px' }}>
        <GlowOrb x="50%" y="0px" color="radial-gradient(circle, #7c3aed, transparent)" size="600px" />
        <div style={{ maxWidth: 1200, margin: '0 auto', position: 'relative', zIndex: 2 }}>
          <div style={{ textAlign: 'center', marginBottom: 64 }}>
            <p style={{ fontSize: 12, color: '#c084fc', fontWeight: 600, letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: 12 }}>
              Features
            </p>
            <h2 style={{ fontSize: 'clamp(28px, 3.5vw, 44px)', fontWeight: 700, color: '#fff', letterSpacing: '-0.02em', margin: '0 0 16px' }}>
              Crafted for the Next Generation
            </h2>
            <p style={{ fontSize: 16, color: '#475569', maxWidth: 480, margin: '0 auto' }}>
              Everything you need to experience music the way it was meant to be heard.
            </p>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 20 }}>
            {FEATURES.map((feature, index) => (
              <div
                key={index}
                style={{
                  background: 'rgba(255,255,255,0.025)',
                  border: '1px solid rgba(147,51,234,0.12)',
                  borderRadius: 16,
                  padding: '28px',
                  cursor: 'pointer',
                  transition: 'border-color 0.22s, background 0.22s, transform 0.22s',
                }}
                onMouseEnter={(e) => {
                  const el = e.currentTarget
                  el.style.borderColor = 'rgba(147,51,234,0.38)'
                  el.style.background = 'rgba(147,51,234,0.07)'
                  el.style.transform = 'translateY(-4px)'
                }}
                onMouseLeave={(e) => {
                  const el = e.currentTarget
                  el.style.borderColor = 'rgba(147,51,234,0.12)'
                  el.style.background = 'rgba(255,255,255,0.025)'
                  el.style.transform = 'translateY(0)'
                }}
              >
                <div
                  style={{
                    width: 44,
                    height: 44,
                    background: 'rgba(147,51,234,0.14)',
                    border: '1px solid rgba(147,51,234,0.24)',
                    borderRadius: 12,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    marginBottom: 18,
                  }}
                >
                  <span style={{ fontSize: 20 }}>{feature.icon}</span>
                </div>
                <h3 style={{ fontSize: 16, fontWeight: 600, color: '#fff', margin: '0 0 10px' }}>{feature.title}</h3>
                <p style={{ fontSize: 14, color: '#475569', lineHeight: 1.65, margin: 0 }}>{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section id="trending" style={{ padding: '80px 80px', position: 'relative', scrollMarginTop: '64px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 36 }}>
            <h2 style={{ fontSize: 28, fontWeight: 700, color: '#fff', letterSpacing: '-0.02em', margin: 0 }}>
              Trending Now
            </h2>
            <button
              onClick={() => alert('View All clicked')}
              style={{ fontSize: 13, color: '#c084fc', background: 'none', border: 'none', padding: 0, cursor: 'pointer' }}
            >
              View All →
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(170px, 1fr))', gap: 18 }}>
            {TRENDING.map((item, index) => (
              <div
                key={index}
                style={{
                  background: 'rgba(255,255,255,0.025)',
                  border: '1px solid rgba(147,51,234,0.1)',
                  borderRadius: 14,
                  overflow: 'hidden',
                  cursor: 'pointer',
                  transition: 'border-color 0.22s, transform 0.22s',
                }}
                onMouseEnter={(e) => {
                  const el = e.currentTarget
                  el.style.borderColor = 'rgba(147,51,234,0.38)'
                  el.style.transform = 'translateY(-3px)'
                }}
                onMouseLeave={(e) => {
                  const el = e.currentTarget
                  el.style.borderColor = 'rgba(147,51,234,0.1)'
                  el.style.transform = 'translateY(0)'
                }}
              >
                <div style={{ position: 'relative', aspectRatio: '1', overflow: 'hidden' }}>
                  <img src={item.img} alt={item.title} style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                  <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(7,7,16,0.8) 0%, transparent 60%)' }} />
                  <div style={{ position: 'absolute', bottom: 10, right: 10, background: 'rgba(147,51,234,0.85)', borderRadius: 999, width: 32, height: 32, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, color: '#fff' }}>▶</div>
                </div>
                <div style={{ padding: '12px 14px' }}>
                  <div style={{ fontSize: 14, fontWeight: 600, color: '#e2e8f0', marginBottom: 3, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{item.title}</div>
                  <div style={{ fontSize: 12, color: '#475569' }}>{item.artist}</div>
                  <div style={{ fontSize: 11, color: '#334155', marginTop: 4 }}>{item.plays} plays</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section style={{ padding: '80px 80px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div
            style={{
              background: 'linear-gradient(135deg, rgba(124,58,237,0.14) 0%, rgba(7,7,16,0.85) 65%)',
              border: '1px solid rgba(147,51,234,0.2)',
              borderRadius: 24,
              padding: '64px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: 48,
              flexWrap: 'wrap',
              position: 'relative',
              overflow: 'hidden',
            }}
          >
            <GlowOrb x="-80px" y="-40px" color="radial-gradient(circle, #7c3aed, transparent)" size="400px" />
            <div style={{ flex: '1 1 360px', position: 'relative', zIndex: 2 }}>
              <h2
                style={{
                  fontSize: 'clamp(28px, 3.5vw, 44px)',
                  fontWeight: 700,
                  lineHeight: 1.15,
                  letterSpacing: '-0.025em',
                  margin: '0 0 20px',
                  color: '#fff',
                }}
              >
                Music That{' '}
                <span
                  style={{
                    background: 'linear-gradient(135deg, #e879f9, #7c3aed)',
                    WebkitBackgroundClip: 'text',
                    WebkitTextFillColor: 'transparent',
                    backgroundClip: 'text',
                  }}
                >
                  Understands You.
                </span>
              </h2>
              <p style={{ fontSize: 16, color: '#94a3b8', lineHeight: 1.75, marginBottom: 36, maxWidth: 440 }}>
                Melodia learns your listening patterns over time to surface music that fits the moment — not just charts, but the right sound for right now.
              </p>
              <div style={{ display: 'flex', gap: 14, flexWrap: 'wrap' }}>
                <button
                  onClick={() => navigate('/login')}
                  style={{
                    background: 'linear-gradient(135deg, #9333ea, #7c3aed)',
                    border: 'none',
                    color: '#fff',
                    fontSize: 14,
                    fontWeight: 600,
                    cursor: 'pointer',
                    padding: '12px 24px',
                    borderRadius: 9,
                    transition: 'transform 0.15s, boxShadow 0.15s',
                    boxShadow: '0 0 24px rgba(147,51,234,0.4)',
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.transform = 'translateY(-2px)'
                    e.currentTarget.style.boxShadow = '0 8px 32px rgba(147,51,234,0.55)'
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.transform = 'translateY(0)'
                    e.currentTarget.style.boxShadow = '0 0 24px rgba(147,51,234,0.4)'
                  }}
                >
                  Start for Free
                </button>
                <button
                  onClick={() => navigate('/login')}
                  style={{
                    background: 'none',
                    border: '1px solid rgba(255,255,255,0.11)',
                    color: '#e2e8f0',
                    fontSize: 14,
                    fontWeight: 500,
                    cursor: 'pointer',
                    padding: '12px 24px',
                    borderRadius: 9,
                    transition: 'background 0.2s',
                  }}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background = 'rgba(255,255,255,0.06)'
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background = 'none'
                  }}
                >
                  Learn More
                </button>
              </div>
            </div>

            <div style={{ flex: '0 0 auto', position: 'relative', zIndex: 2 }}>
              <BrainVisual />
            </div>
          </div>
        </div>
      </section>

      <footer id="contact" style={{ borderTop: '1px solid rgba(147,51,234,0.1)', padding: '60px 80px 40px', scrollMarginTop: '64px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr', gap: 48, marginBottom: 48 }} className="footer-grid">
            <div>
              <button
                onClick={() => scrollTo('hero')}
                style={{ display: 'flex', alignItems: 'center', gap: 10, background: 'none', border: 'none', cursor: 'pointer', padding: 0, marginBottom: 16 }}
              >
                <MelodiaLogo size={32} />
                <span style={{ fontSize: 17, fontWeight: 700 }}>
                  <span style={{ color: '#fff' }}>Melo</span>
                  <span style={{ background: 'linear-gradient(135deg, #c084fc, #7c3aed)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>
                    dia
                  </span>
                </span>
              </button>
              <p style={{ fontSize: 14, color: '#334155', lineHeight: 1.7, maxWidth: 240, marginBottom: 24 }}>
                Music streaming built for the next generation of listeners.
              </p>
              <div style={{ display: 'flex', gap: 10 }}>
                {['𝕏', 'in', 'f', '▶'].map((icon, index) => (
                  <div
                    key={index}
                    style={{
                      width: 34,
                      height: 34,
                      background: 'rgba(255,255,255,0.04)',
                      border: '1px solid rgba(147,51,234,0.15)',
                      borderRadius: 8,
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: 13,
                      color: '#64748b',
                      cursor: 'pointer',
                      transition: 'border-color 0.2s, color 0.2s',
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.borderColor = 'rgba(147,51,234,0.4)'
                      e.currentTarget.style.color = '#c084fc'
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.borderColor = 'rgba(147,51,234,0.15)'
                      e.currentTarget.style.color = '#64748b'
                    }}
                  >
                    {icon}
                  </div>
                ))}
              </div>
            </div>

            {[
              { title: 'Product', links: ['Features', 'Pricing', 'Changelog', 'Roadmap'] },
              { title: 'Company', links: ['About', 'Blog', 'Careers', 'Press'] },
              { title: 'Legal', links: ['Privacy', 'Terms', 'Cookies', 'Licenses'] },
            ].map((col) => (
              <div key={col.title}>
                <h4 style={{ fontSize: 12, fontWeight: 600, color: '#e2e8f0', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 18 }}>
                  {col.title}
                </h4>
                <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 12 }}>
                  {col.links.map((link) => (
                    <li key={link}>
                      <button
                        type="button"
                        style={{
                          fontSize: 14,
                          color: '#334155',
                          background: 'none',
                          border: 'none',
                          padding: 0,
                          textAlign: 'left',
                          cursor: 'pointer',
                        }}
                        onMouseEnter={(e) => (e.currentTarget.style.color = '#94a3b8')}
                        onMouseLeave={(e) => (e.currentTarget.style.color = '#334155')}
                      >
                        {link}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div
            style={{
              background: 'rgba(147,51,234,0.06)',
              border: '1px solid rgba(147,51,234,0.14)',
              borderRadius: 14,
              padding: '28px 32px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: 20,
              flexWrap: 'wrap',
              marginBottom: 40,
            }}
          >
            <div>
              <div style={{ fontSize: 16, fontWeight: 600, color: '#fff', marginBottom: 4 }}>Get in touch</div>
              <div style={{ fontSize: 14, color: '#475569' }}>
                Have a question or feedback? We'd love to hear from you.
              </div>
            </div>
            <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
              <input
                placeholder="your@email.com"
                style={{
                  background: 'rgba(255,255,255,0.05)',
                  border: '1px solid rgba(147,51,234,0.2)',
                  borderRadius: 8,
                  padding: '10px 16px',
                  color: '#e2e8f0',
                  fontSize: 14,
                  outline: 'none',
                  width: 220,
                }}
                onFocus={(e) => (e.currentTarget.style.borderColor = 'rgba(147,51,234,0.5)')}
                onBlur={(e) => (e.currentTarget.style.borderColor = 'rgba(147,51,234,0.2)')}
              />
              <button
                type="button"
                style={{
                  background: 'linear-gradient(135deg, #9333ea, #7c3aed)',
                  border: 'none',
                  color: '#fff',
                  fontSize: 14,
                  fontWeight: 600,
                  cursor: 'pointer',
                  padding: '10px 22px',
                  borderRadius: 8,
                  transition: 'opacity 0.2s',
                }}
                onMouseEnter={(e) => (e.currentTarget.style.opacity = '0.85')}
                onMouseLeave={(e) => (e.currentTarget.style.opacity = '1')}
              >
                Send Message
              </button>
            </div>
          </div>

          <div style={{ borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: 24, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
            <span style={{ fontSize: 13, color: '#1e293b' }}>© 2025 Melodia, Inc. All rights reserved.</span>
            <span style={{ fontSize: 13, color: '#1e293b' }}>Made with ♥ for music lovers</span>
          </div>
        </div>
      </footer>

      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
        * { box-sizing: border-box; }
        html { scroll-behavior: smooth; }
        body { margin: 0; }
        #hero, #features, #trending, #contact { scroll-margin-top: 64px; }
        ::-webkit-scrollbar { width: 5px; }
        ::-webkit-scrollbar-track { background: #070710; }
        ::-webkit-scrollbar-thumb { background: rgba(147,51,234,0.4); border-radius: 3px; }
        @media (max-width: 768px) {
          .nav-links { display: none !important; }
          .footer-grid { grid-template-columns: 1fr 1fr !important; }
        }
        @media (max-width: 600px) {
          .footer-grid { grid-template-columns: 1fr !important; }
        }
      `}</style>
    </div>
  )
}
